"""Fix timestamp defaults for SQLite compatibility

Revision ID: 18aa536e3fa1
Revises: f1ea596b1427
Create Date: 2025-09-19 18:21:30.745680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18aa536e3fa1'
down_revision: Union[str, Sequence[str], None] = 'f1ea596b1427'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking_sessions',
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('workstation_id', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('zone_history', sa.JSON(), nullable=True),
    sa.Column('total_detections', sa.Integer(), nullable=False),
    sa.Column('zones_visited', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('current_zone_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['current_zone_id'], ['zones.id'], ),
    sa.ForeignKeyConstraint(['workstation_id'], ['workstations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracking_sessions_id'), 'tracking_sessions', ['id'], unique=False)
    op.add_column('detections', sa.Column('track_ids', sa.JSON(), nullable=True))
    op.add_column('detections', sa.Column('tracking_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detections', 'tracking_data')
    op.drop_column('detections', 'track_ids')
    op.drop_index(op.f('ix_tracking_sessions_id'), table_name='tracking_sessions')
    op.drop_table('tracking_sessions')
    # ### end Alembic commands ###
